### ISSUE TITLE
Make title go to join game page

### ISSUE THREAD

**Issue by KTSCode** [Jman012/Inf122-BoardGames-Client#20]
the title on the app bar should take you to the homepage (join game page)

**Comment by alvinherot** [comment]
I attempted this and the problem is that if the game is underway and they get redirected, they will not be able to rejoin their game because their game is full(full games do not show up in join). It does work fine when they are in the "Waiting game screen" though.

**Comment by KTSCode** [comment]
I have a conditional that will take you to the join page if your not in a game and will take you to your game if you are currently in one
